version: "3.8"

volumes:
  mongodata2:
  mongodata3:

networks:
  default:
    external:
      name: mongo

services:
  mongo1:
    image: mongo:4.4.1
    volumes:
      - ~/mongo-conf:/mongo-conf
      - /mnt/volume_nyc3_01:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27017:27017
    command: 'mongod --auth --keyFile /mongo-conf/mongo_replica_keys.yml --replSet rs0 --bind_ip mongo1'
    deploy:
      placement:
        constraints:
          - "node.labels.mongo.replica == 1"
  mongo2:
    image: mongo:4.4.1
    volumes:
      - ~/mongo-conf:/mongo-conf
      - mongodata2:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27018:27017
    command: 'mongod --auth --keyFile /mongo-conf/mongo_replica_keys.yml --replSet rs0 --bind_ip mongo2'
    deploy:
      placement:
        constraints:
          - "node.labels.mongo.replica == 2"
  mongo3:
    image: mongo:4.4.1
    volumes:
      - ~/mongo-conf:/mongo-conf
      - mongodata3:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27019:27017
    command: 'mongod --auth --keyFile /mongo-conf/mongo_replica_keys.yml --replSet rs0 --bind_ip mongo3'
    deploy:
      placement:
        constraints:
          - "node.labels.mongo.replica == 3"