version: "3.1"

volumes:
  mongodata2:
  mongodata3:

networks:
  default:
    external:
      name: mongo

secrets:
  mongo-replica-keys:
    file: ./mongo_replica_keys.yml

services:
  mongo1:
    image: mongo:4.4.1
    volumes:
      - /mnt/volume_nyc3_01:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27017:27017
    secrets:
      - source: mongo-replica-keys
        mode: 0600
    command: 'mongod --auth --keyFile /run/secrets/mongo-replica-keys --replSet rs0'
    deploy:
      placement:
        constraints:
          - "node.labels.mongo.replica == 1"
  mongo2:
    image: mongo:4.4.1
    volumes:
      - mongodata2:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27018:27017
    secrets:
      - source: mongo-replica-keys
        mode: 0600
    command: 'mongod --auth --keyFile /run/secrets/mongo-replica-keys --replSet rs0'
    deploy:
      placement:
        constraints:
          - "node.labels.mongo.replica == 2"
  mongo3:
    image: mongo:4.4.1
    volumes:
      - mongodata3:/data/db
    env_file:
      ./mongod.env
    ports:
      - 27019:27017
    secrets:
      - source: mongo-replica-keys
        mode: 0600
    command: 'mongod --auth --keyFile /run/secrets/mongo-replica-keys --replSet rs0'
    deploy:
      placement:
        constraints:
          - "node.labels.mongo.replica == 3"